config/routes.rb
Rails.application.routes.draw do
  # get 'collaborator/new'
  # get 'collaborator/create'
  # get 'collaborator/destroy'
  resources :charges, only: [:new, :create]
  resources :wikis
  resources :collaborators
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  get 'about' => 'welcome#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    if current_user.account == 'free'
      flash[:notice] = "You are already on the Free Plan!"
      redirect_to root_path
    else
      @user = User.find(current_user.id)
      @user.account = 'free'
      if @user.save
        Wiki.where(:user_id => current_user.id, :private => true).each do |wiki|
          wiki.private = false
          wiki.save
        end 
        flash[:notice] = "You have been downgraded to the Free Plan and your private wikis are no longer private!"
        redirect_to wikis_path # or wherever
      end
    end 
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
    <div class="col-md-12 text-center">
        <h2>Blocipedia: Social, Markdown Wikis</h2>
    </div>


    <div class="col-md-12 text-center">
        <h4>Create and share Markdown Wikis</h4>
    </div>

    <div class="col-md-12 text-center">
        <% if current_user %>
            <%= link_to "View Wikis", wikis_path %>
        <% else %>
            <button type="button" class="btn btn-outline-primary">
            <%= button_to "Sign Up", new_user_registration_path, :class => 'navbar-link', :method => :get %>
            </button>
        <% end %>
    </div>
    <% if current_user %>
        <div class="row"> 
            <div class="col-md-6 text-right">
                <h5>Create as many public </br> wikis as you want!</h5>
            </div>
            <div class="col-md-6 text-left">
                <h5>Create private wikis!</h5>
            </div>
        </div>

        <div class="col-md-6 text-right">
            <button type="button" class="btn btn-outline-primary">
            <%= button_to "Free Plan", about_path, :method => :get %>
            </button>
        </div>
        <div class="col-md-6 text-left">
            <button type="button" class="btn btn-success">
            <%= button_to "Premium Plan", new_charge_path, :method => :get %>
            </button>
        </div>
    <% end %>
</div>