config/routes.rb
Rails.application.routes.draw do
  # get 'collaborator/new'
  # get 'collaborator/create'
  # get 'collaborator/destroy'
  resources :charges, only: [:new, :create]
  resources :wikis
  resources :collaborators
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  get 'about' => 'welcome#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  has_many :collaborators
  has_many :users, through: :collaborators

  belongs_to :user
  before_save {self.private ||= false }
  validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 20 }, presence: true

   delegate :users, to: :collaborators

  #  def collaborators
  #   Collaborator.where(wiki_id: id)
  #  end 

  #  def users
  #   collaborators.users
  #  end 

  end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    # if current_user.admin? || current_user.premium?
    #   @wikis = Wiki.all
    # else 
    #   @wikis = Wiki.where(private: false)
    # end
    @wikis = policy_scope(Wiki)
    # authorize @wikis
    
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
    @collaborator = Collaborator.new
  end

  def create
    # @wiki = Wiki.new
    # @wiki.title = params[:wiki][:title]
    # @wiki.body = params[:wiki][:body]
    # @wiki.private = params[:wiki][:private]
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end 

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @collaborator = Collaborator.find_by(wiki_id: @wiki.id)
  end

  def update
    @wiki = Wiki.find(params[:id])
    # @wiki.title = params[:wiki][:title]
    # @wiki.body = params[:wiki][:body]
    @wiki.assign_attributes(wiki_params)
    
    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end 

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end 

  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_collaborators.html.erb
<%= form_for @wiki do |f| %>
    <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
            Collaborators: <br>
            <% @wiki.collaborators.each do |c| %>
            <% user = User.find(c.user_id) %>
            <%= f.label user.email %>
            <%= f.text_field user.email, class: 'form-control', placeholder: "Enter collaborator email" %>
            <% end %>
        </div>
    <% end %>
    
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>

    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> 
        Private wiki
        <% end %>
      </div>
      
    <% end %>
    
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<% if current_user %>
    
    <div>
        Collaborators: <br>
        <% @wiki.collaborators.each do |c| %>
            <% user = User.find(c.user_id) %>
            <p><%= user.email %></p>
            <%= link_to "Delete", c, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this collaborator?'} %>
        <% end %>
    </div>
    <div>
            <%= form_for Collaborator.new do |f| %>
                <p><%= f.text_field :email, class: 'form-control' %></p>
                
                <%= f.hidden_field :wiki_id, :value => @wiki.id %>
                <%= f.hidden_field :user_id, :value => @wiki.user_id %>
                <%= f.submit 'Add Collaborator' %>
            <% end %>
    </div>
<% end %>
<div class="col-md-8">
     <%= render partial: 'form', locals: { wiki: @wiki } %>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<% if current_user %>
  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  
    <% @wikis.each do |wiki| %>
        <p><%= link_to wiki.title, wiki_path(wiki.id) %>
        <%= wiki.id %>
        <% if wiki.private %>
            Private 
        <% end %></p>
    <% end %>
</div>
<% end %>

app/views/wikis/new.html.erb
<div class="col-md-8">
  <%= render partial: 'form', locals: { wiki: @wiki }  %>
</div>

app/views/wikis/show.html.erb
<%= link_to "Back to Wikis", wikis_path %>
<div>
    <h1><%= @wiki.title %></h1>
    <% if @wiki.private == true %>
        <p>Private</p>    
    <% end %>
</div>

<div class="row">
    <div class="col-md-8">
        <%= markdown(@wiki.body) %>
    </div>
    <div class="col-md-4">
    <% # added @wiki.user_id to edit path and displayed on screen %>
        <%= link_to "Edit", edit_wiki_path(@wiki,@wiki.user_id), class: 'btn btn-success' %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    </div>
</div>